TaxCalculator.Web/Models/TaxCalculateViewModel.cs
using System.ComponentModel.DataAnnotations;
using TaxCalculator.Service.Dto;

namespace TaxCalculator.Web.Models
{
    public class TaxCalculateViewModel
    {
        [Required]
        [Display(Name = "Taxable income")]
        [RegularExpression("^[0-9]+$", ErrorMessage = "Must be a number without digits")]

        [DataType(DataType.Currency)]
        public int? TaxableIncome { get; set; }

        [Display(Name = "Financial year")]
        public int SelectedYear { get; set; }
        public Result Result { get; set; }
    }
}

TaxCalculator.Web/Controllers/BaseController.cs
using System.Web.Mvc;
using TaxCalculator.Dal;

namespace TaxCalculator.Web.Controllers
{
    public class BaseController : Controller
    {
        public TaxCalculatorContext TaxCalculatorContext { get; set; }

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);

            TaxCalculatorContext = (TaxCalculatorContext)HttpContext.Items["CurrentRequestDataContext"];
        }

        protected void ShowInfoMessage(string message)
        {
            ViewBag.InfoMessage = message;
        }

        protected void ShowWarningMessage(string message)
        {
            ViewBag.WarningMessage = message;
        }

        protected void ShowErrorMessage(string message)
        {
            ViewBag.ErrorMessage = message;
        }
    }
}

TaxCalculator.Web/Controllers/CalculatorController.cs
using System.Linq;
using System.Web.Mvc;
using TaxCalculator.Service.Iterfaces;
using TaxCalculator.Web.Models;

namespace TaxCalculator.Web.Controllers
{
    public class CalculatorController : BaseController
    {
        private readonly ICalculateService _calculateService;

        public CalculatorController(ICalculateService calculateService)
        {
            _calculateService = calculateService;
        }

        public ActionResult Index()
        {
            var list = TaxCalculatorContext.TaxRates
                .OrderByDescending(r => r.Year)
                .ToArray()
                .Select(r => new SelectListItem
                {
                    Text = r.Description,
                    Value = r.Id.ToString(),
                });

            ViewBag.TaxRatesList = list;

            return View();
        }

        [HttpPost]
        public ActionResult Index(TaxCalculateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var taxRate = TaxCalculatorContext.TaxRates.Find(model.SelectedYear);
                if (taxRate == null)
                    return HttpNotFound();

                model.Result = _calculateService.Calculate(taxRate, model.TaxableIncome.Value);
            }
            else
            {
                ShowErrorMessage("Please input valid data");
            }

            var list = TaxCalculatorContext.TaxRates
                .OrderByDescending(r => r.Year)
                .ToArray()
                .Select(r => new SelectListItem
                {
                    Text = r.Description,
                    Value = r.Id.ToString(),
                });

            ViewBag.TaxRatesList = list;

            return View(model);
        }
    }
}

TaxCalculator.Web/Controllers/HomeController.cs
using System.Web.Mvc;

namespace TaxCalculator.Web.Controllers
{
    public class HomeController : BaseController
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

TaxCalculator.Web/Controllers/TaxRateController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Mvc;
using TaxCalculator.Domain;

namespace TaxCalculator.Web.Controllers
{
    public class TaxRateController : BaseController
    {
        public ActionResult Index()
        {
            var list = TaxCalculatorContext.TaxRates
                .OrderByDescending(r => r.Year)
                .ToArray();

            return View(list);
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var taxRate = TaxCalculatorContext.TaxRates.Find(id);

            if (taxRate == null)
                return new HttpNotFoundResult();

            return View(taxRate);
        }

        [HttpGet]
        public ActionResult Add()
        {
            var taxRate = new TaxRate
            {
                Items = new List<TaxRateItem>
                {
                    new TaxRateItem()
                    {
                        Thresholds = new List<TaxThreshold>
                        {
                            new TaxThreshold(),
                            new TaxThreshold(),
                            new TaxThreshold(),
                        }
                    }
                }
            };

            return View(taxRate);
        }

        [HttpPost]
        public ActionResult Add(TaxRate taxRate)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TaxCalculatorContext.TaxRates.Add(taxRate);
                    taxRate.CreateAt = DateTime.Now;

                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                ShowErrorMessage(ex.Message);
            }

            return View(taxRate);
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var taxRate = TaxCalculatorContext.TaxRates.Find(id);

            if (taxRate == null)
                return new HttpNotFoundResult();

            return View(taxRate);
        }

        [HttpPost]
        public ActionResult Edit(TaxRate taxRate)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    TaxCalculatorContext.Entry(taxRate).State = EntityState.Modified;
                    ShowInfoMessage("Tax rate saved successfully");
                }
            }
            catch (Exception ex)
            {
                ShowErrorMessage(ex.Message);
            }

            return View(taxRate);
        }

        [HttpPost]
        public HttpResponseMessage Delete(int id)
        {
            var taxRate = TaxCalculatorContext.TaxRates.Find(id);

            if (taxRate == null)
                return new HttpResponseMessage(HttpStatusCode.NotFound);

            TaxCalculatorContext.TaxRates.Remove(taxRate);

            return new HttpResponseMessage(HttpStatusCode.OK);
        }
    }
}

TaxCalculator.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TaxCalculator.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TaxCalculator.Web/Views/Home/Index.cshtml
<div class="jumbotron text-center" style="background: none; margin-top: 20px;">
    <span class="fa fa-coffee" style="font-size: 5em;"></span>
    <p class="welcome-header">
        TAX<span style="color: #cc0000">C</span>ALCULATOR
    </p>
    <p class="text-center" style="width: 80%; font-size: 22px; margin: auto; color: #666;">
        A personal income tax calculator which is based on configurable tax rates settings aiming to corp with the tax rates frequent changes
    </p>
</div>
<div class="row text-center margin-bottom-25">
    <a href="@Url.Action("Index", "Calculator")" class="btn btn-default btn-lg text-center" style="width:220px; padding: 10px;">START NOW</a>
</div>

TaxCalculator.Web/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Tax Calculator</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <header class="site-header">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <span class="navbar-brand">
                    <a href="@Url.Action("Index", "Home")">
                        <i class="fa fa-coffee fa-lg"></i>
                        TAX<span style="color: #cc0000">C</span>ALCULATOR
                    </a>
                </span>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="@Url.Action("Index", "Home")">
                            <i class="fa fa-home fa-lg"></i>
                            Home
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "Calculator")">
                            <i class="fa fa-calculator fa-lg"></i>
                            Calculator
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "TaxRate")">
                            <i class="fa fa-cog fa-lg"></i>
                            Tax Rate
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </header>
    <div class="content-container">
        <div class="container body-content">
            @Html.Partial("_MessagePanel")
            <div id="alertDiv" class="alert alert-danger margin-top-5" style="display: none;">
                <a href="#" class="close" data-dismiss="alert">&times;</a>
                <span id="alertText">test</span>
            </div>
            @if (!string.IsNullOrEmpty(ViewBag.Title))
            {
                <h1>@ViewBag.Title</h1>
            }

            <div class="margin-top-25">
                @RenderBody()
            </div>
        </div>
    </div>

    <footer>
        <div class="container">
            <i class="fa fa-coffee fa-lg"></i>
            <p>
                Fork this project in <a href="https://github.com/stephenzeng/StephenZeng.TaxCalculator"><i class="fa fa-github"></i> GitHub</a>
                <br>
                Contact me at zeng.stephen@gmail.com
                <br />
                <span class="fa fa-copyright"> @DateTime.Now.Year</span>
            </p>
        </div>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TaxCalculator.Web/Views/Shared/_MessagePanel.cshtml
@if (!string.IsNullOrEmpty(ViewBag.InfoMessage))
{
    <div class="alert alert-info alert-dismissible margin-top-5" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
        </button>
        @ViewBag.InfoMessage
    </div>
}

@if (!string.IsNullOrEmpty(ViewBag.WarningMessage))
{
    <div class="alert alert-warning alert-dismissible margin-top-5" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
        </button>
        <strong>WARNING:</strong> @ViewBag.WarningMessage
    </div>
}

@if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
{
    <div class="alert alert-danger alert-dismissible margin-top-5" role="alert">
        <button type="button" class="close" data-dismiss="alert">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
        </button>
        <strong>ERROR:</strong> @ViewBag.ErrorMessage
    </div>
}

TaxCalculator.Web/Views/TaxRate/Add.cshtml
@{
    ViewBag.Title = "Add";
}

<h2>Add</h2>

TaxCalculator.Web/Views/TaxRate/Details.cshtml
@model TaxCalculator.Domain.TaxRate

<div class="panel panel-default">
    <div class="panel-heading">
        <span class="fa fa-tag"></span>
        @Model.Description
    </div>

    @if (Model.Items != null)
    {
        <div class="panel-body">
            @foreach (var item in Model.Items)
            {
                <div class="col-sm-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <span class="fa fa-tag"></span>
                            @item.Description
                        </div>
                        <div class="panel-body">
                            @if (item.Thresholds != null)
                            {
                                <table class="table table-striped table-condensed margin-bottom-0">
                                    <thead>
                                        <tr>
                                            <th>Start</th>
                                            <th>End</th>
                                            <th>Rate</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @foreach (var threshold in item.Thresholds)
                                        {
                                            <tr>
                                                <td>@threshold.Start.ToString("C")</td>
                                                <td>@(threshold.End.HasValue ? threshold.End.Value.ToString("C") : string.Empty)</td>
                                                <td>@threshold.Rate.ToString("p")</td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                            }
                        </div>
                    </div>
                </div>
            }
        </div>
    }
</div>

TaxCalculator.Web/Views/TaxRate/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

TaxCalculator.Web/Views/TaxRate/Index.cshtml
@model IEnumerable<TaxCalculator.Domain.TaxRate>

@{
    ViewBag.Title = "Tax Rates";
}

<div class="panel panel-default margin-top-5">
    <div class="panel-heading">
        <span class="fa fa-tags"></span>
        @ViewBag.Title
    </div>
    <div class="panel-body">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th></th>
                    <th>Year</th>
                    <th>Description</th>
                    <th>Create time</th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    foreach (var taxRate in Model)
                    {
                        <tr>
                            <td style="width: 100px;">
                                <a href="@Url.Action("Details", "TaxRate", new {taxRate.Id}, null)" title="View">
                                    <span class="fa fa-file-text-o"></span> View
                                </a>
                            </td>
                            <td>@taxRate.Year</td>
                            <td>@taxRate.Description</td>
                            <td>@Html.DisplayFor(m => taxRate.CreateAt)</td>
                        </tr>
                    }
                }
            </tbody>
        </table>
    </div>
</div>